"""Build corrected course PDFs. Optional deps: reportlab, pymupdf (rendering)."""
from pathlib import Path
import json
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, Table, TableStyle, PageBreak, Image
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT

ROOT=Path(__file__).resolve().parents[1]
ST=getSampleStyleSheet()
ST.add(ParagraphStyle(name='DocTitle',fontName='Helvetica-Bold',fontSize=23,leading=28,textColor=colors.HexColor('#123445'),spaceAfter=14))
ST.add(ParagraphStyle(name='Section',fontName='Helvetica-Bold',fontSize=13,leading=17,textColor=colors.HexColor('#007f8b'),spaceBefore=13,spaceAfter=7))
ST.add(ParagraphStyle(name='Copy',fontName='Helvetica',fontSize=10,leading=14,spaceAfter=8))
ST.add(ParagraphStyle(name='Equation',fontName='Courier',fontSize=8.6,leading=12,spaceBefore=5,spaceAfter=10,backColor=colors.HexColor('#f1f5f9'),borderPadding=8))

def para(text): return Paragraph(text,ST['Copy'])
def section(text): return Paragraph(text,ST['Section'])
def equation(text): return Preformatted(text,ST['Equation'])
def title(text,sub): return [Paragraph(text,ST['DocTitle']),para(sub)]
def footer(canvas,doc):
    canvas.setStrokeColor(colors.HexColor('#cbd5e1'));canvas.line(45,40,567,40)
    canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#475569'))
    canvas.drawString(45,27,'ME 4030 | Quarter-Car Control Lab | Corrected edition, September 2026')
    canvas.drawRightString(567,27,str(doc.page))
def table(rows,widths):
    data=[[Paragraph(escape(str(v)),ST['Copy']) for v in row] for row in rows]
    t=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e0f2f1')),('VALIGN',(0,0),(-1,-1),'TOP'),('LINEBELOW',(0,0),(-1,0),.6,colors.HexColor('#007f8b')),('BOTTOMPADDING',(0,0),(-1,-1),5),('TOPPADDING',(0,0),(-1,-1),5),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f8fafc')])]))
    return t

def save(path,story):
    SimpleDocTemplate(str(ROOT/path),pagesize=(612,792),rightMargin=45,leftMargin=45,topMargin=43,bottomMargin=55,title=Path(path).stem.replace('-',' ').title(),author='Sriram Krishnamoorthy').build(story,onFirstPage=footer,onLaterPages=footer)

PARAMS=[['Parameter','Value','Meaning'],['Ms','2500 kg','Sprung (body) mass'],['Mu','320 kg','Unsprung (wheel assembly) mass'],['Ks','80000 N/m','Suspension stiffness'],['Cs','350 N s/m','Suspension damping'],['Kt','500000 N/m','Tire stiffness'],['Ct','15020 N s/m','Tire damping']]
EOM='Ms*zs_ddot = -Ks*(zs-zu) - Cs*(zs_dot-zu_dot) + u\nMu*zu_ddot =  Ks*(zs-zu) + Cs*(zs_dot-zu_dot)\n             - Kt*(zu-zr) - Ct*(zu_dot-zr_dot) - u'
A_TEXT='alpha = Cs/Ms + Cs/Mu + Ct/Mu\n\nA = [ 0,              1,  0,                         0;\n     -Cs*Ct/(Ms*Mu),  0,  Cs*alpha/Ms-Ks/Ms,        -Cs/Ms;\n      Ct/Mu,          0, -alpha,                     1;\n      Kt/Mu,          0, -(Ks/Ms+Ks/Mu+Kt/Mu),       0 ]\n\nBu = [0; 1/Ms; 0; 1/Ms+1/Mu]\nBw = [0; Cs*Ct/(Ms*Mu); -Ct/Mu; -Kt/Mu]\nC  = [0, 0, 1, 0]'
DELTA='D(p) = (Ms*p^2+Cs*p+Ks)*(Mu*p^2+(Cs+Ct)*p+Ks+Kt)\n       - (Cs*p+Ks)^2\n\nGu(p) = S(p)/U(p)  = ((Ms+Mu)*p^2+Ct*p+Kt)/D(p)\nGw(p) = S(p)/Zr(p) = -Ms*p^2*(Ct*p+Kt)/D(p)'

story=title('Active Suspension Design','Senior-level controls project | ME 4030 | Sriram Krishnamoorthy')
story += [para('Design and evaluate PID and LQR controllers for a quarter-car suspension. This corrected public edition preserves the original project scope and grading weights while clarifying signs, states, and performance measures.'),section('System and assumptions'),para('Model small vertical motions about static equilibrium with linear springs and dampers. The road displacement zr is a disturbance. The actuator applies +u to the body and -u to the wheel. Assume an ideal force actuator; discuss the limits of this assumption.'),table(PARAMS,[70,110,342]),section('Equations of motion'),equation(EOM),para('Use suspension deflection s = zs - zu and tire deflection h = zu - zr. Tire forces are restoring: their signs in the wheel equation are negative for positive h and h_dot.'),section('Road inputs and initial conditions'),para('Use zero initial conditions and a 10 s record. The step road rises by 0.2 m at t = 1 s. The sinusoidal road is zr(t) = 0.1 sin(2 pi 0.5 t) m. Report the simulation method and output time step. A sharp step with tire damping and ideal derivative feedback can create a very fast transient.'),PageBreak()]
story += title('Performance measures','Evaluate tradeoffs; do not assume that every benchmark can be met simultaneously.')
story += [para('Compute RMS values over the full 10 s record. Let RMS(v) = sqrt((1/T) integral from 0 to T of v(t)^2 dt). Body acceleration is absolute vertical acceleration, not acceleration relative to the road.'),table([['Metric','Excellent','Good','Acceptable'],['Body acceleration RMS','<= 0.35 m/s^2','<= 0.50 m/s^2','<= 0.70 m/s^2'],['Tire deflection RMS','<= 0.008 m','<= 0.012 m','<= 0.020 m'],['Peak |s|','<= 0.015 m','<= 0.025 m','<= 0.040 m'],['Actuator force RMS','<= 1.5 kN','<= 2.5 kN','<= 3.5 kN'],['Suspension recovery time','<= 3 s','<= 5 s','<= 7 s']],[174,116,116,116]),section('Step-transient definitions'),para('<b>Suspension recovery:</b> the first time after the road step beyond which |s| remains at or below 0.004 m through the end of the simulation. Measure time from t = 1 s. This is an absolute band equal to 2% of the road-step height. If the trajectory has not recovered by 10 s, report "not settled within the record".'),para('<b>Percentage overshoot of s:</b> do not report it relative to a zero final value; that normalization is undefined. Report peak |s| and recovery instead.'),para('<b>Supplemental body metrics:</b> report body overshoot as 100 max(0, max(zs)-0.2)/0.2 and body settling within 0.2 +/- 0.004 m. These are body-motion metrics, not suspension-deflection metrics. Do not apply step overshoot or settling definitions to the sinusoidal run.'),section('Comparison table'),para('For passive, PID, and LQR cases, report the five benchmark metrics above, peak actuator force, supplemental body metrics, controller parameters, and which benchmarks were met. Mark failed targets explicitly. These are instructional benchmarks, not certified vehicle comfort or safety standards.'),section('Numerical accuracy'),para('A 1 ms output grid is convenient for plots but may miss fast energy contributions. Check convergence or integrate squared outputs on each interval. The reference solution uses exact matrix-exponential propagation and interval energy integrals.'),PageBreak()]
story += title('Design tasks and deliverables','Task 1: 30 points | Task 2: 30 points | Task 3: 40 points')
story += [section('Task 1 - PID design (30 points)'),para('(a) Derive Gu(p) = S(p)/U(p) with zr = 0 and Gw(p) = S(p)/Zr(p) with u = 0. Use the same output sign in both.'),para('(b) Study the passive response to the 0.2 m road step and the force-to-deflection impulse response with zero road input. State the impulse units and magnitude.'),para('(c) Tune a PID controller on suspension deflection. Report Kp, Ki, Kd, the feedback sign, and whether derivative filtering is used. MATLAB pidTuner is optional. Its reference-tracking plot is not the road-disturbance response.'),para('(d) Simulate the closed loop under the specified road inputs and assess the benchmark metrics. Discuss force spikes and practical derivative filtering.'),section('Task 2 - LQR design (30 points)'),para('(a) Derive the state-space model with x = [zs, zs_dot, s, eta]^T using the transformed state defined in the model handout. Identify the actuator and disturbance channels, assess stability, and test controllability.'),para('(b) Simulate the passive sinusoidal response. Recover physical velocities from the transformed state correctly.'),para('(c) Augment the model with xi_dot = s, choose Q >= 0 and R > 0, and compute an LQR gain. Report Q, R, K and closed-loop poles. Explain the meaning of each state weight.'),para('(d) Simulate step and sinusoidal road disturbances and compare with the passive and PID cases. Identify each achieved and unmet target.'),section('Task 3 - Analysis and discussion (40 points)'),para('(a) Explain ride-comfort versus road-holding tradeoffs. (b) Discuss suspension travel, actuator force and practical limits. (c) Assess robustness using evidence, such as varying parameters or disturbances; nominal simulations alone do not establish robustness. (d) Discuss how gain scheduling, data-driven tuning or road preview could help, including data requirements and reliability concerns.'),section('Deliverable and learning outcomes'),para('Submit one PDF containing the model derivation, controller design, code excerpts, plots, comparison tables and discussion. Students should demonstrate mechanical modeling, state interpretation, PID/LQR design, integral augmentation, numerical validation, and clear engineering communication.'),para('Starter: starter/main_file.m. Reference implementation and solution guide: solutions/. MATLAB with Control System Toolbox is required for the controller workflow; pidTuner for an LTI plant is included in Control System Toolbox.')]
save('docs/project.pdf',story)

story=title('Quarter-Car State-Space Model','Corrected derivation | Physical coordinates and road-derivative elimination')
story += [section('1. Force balance'),equation(EOM),para('All displacements use the same upward-positive coordinate and are measured from static equilibrium. Define s = zs - zu. The Laplace variable is denoted p to avoid confusion with suspension deflection s.'),section('2. Physical state model'),equation('q = [zs; vs; zu; vu],   vs = zs_dot, vu = zu_dot\nq_dot = Ap*q + bp*u + wp*zr + dp*zr_dot\n\nAp = [0,       1,       0,           0;\n     -Ks/Ms,  -Cs/Ms,   Ks/Ms,       Cs/Ms;\n      0,       0,       0,           1;\n      Ks/Mu,   Cs/Mu, -(Ks+Kt)/Mu, -(Cs+Ct)/Mu]\n\nbp = [0; 1/Ms; 0; -1/Mu]\nwp = [0; 0; 0; Kt/Mu]\ndp = [0; 0; 0; Ct/Mu]'),para('This physical model explicitly needs road velocity. An ideal road step has an impulsive road velocity, causing a wheel-velocity jump. The transformed coordinates below absorb this input derivative.'),section('3. Relative-motion equation'),equation('s_ddot = (1/Ms+1/Mu)*u - (Ks/Ms+Ks/Mu)*s\n         - (Cs/Ms+Cs/Mu)*s_dot\n         + (Kt/Mu)*(zs-s-zr)\n         + (Ct/Mu)*(zs_dot-s_dot-zr_dot)'),PageBreak()]
story += title('Transformed coordinates','The fourth state is an auxiliary coordinate, not a physical velocity.')
story += [section('4. Define the transformed state'),equation('alpha = Cs/Ms + Cs/Mu + Ct/Mu\neta = s_dot - (Ct/Mu)*zs + alpha*s + (Ct/Mu)*zr\nx = [zs; zs_dot; s; eta]'),para('Differentiate eta and substitute the relative-motion equation. The terms in zs_dot, s_dot and zr_dot cancel exactly:'),equation('eta_dot = (Kt/Mu)*zs - (Ks/Ms+Ks/Mu+Kt/Mu)*s\n          + (1/Ms+1/Mu)*u - (Kt/Mu)*zr\n\ns_dot = (Ct/Mu)*zs - alpha*s + eta - (Ct/Mu)*zr'),para('Substitute this expression for s_dot into the body force balance. Together with zs_dot = x2, this gives x_dot = A*x + Bu*u + Bw*zr and s = C*x:'),equation(A_TEXT),section('5. Recover physical motion'),equation('zs = x1;  zs_dot = x2;  zu = x1-x3\ns_dot = A(3,:)*x + Bw(3)*zr\nzu_dot = zs_dot - s_dot\nzs_ddot = (-Ks*s - Cs*s_dot + u)/Ms'),para('For a road jump dzr, the transformed x remains continuous. The recovered wheel velocity jumps by (Ct/Mu)*dzr. This is a consequence of the ideal tire damper and ideal discontinuous road, not a state-integration error.'),PageBreak()]
story += title('Transfer functions and checks','Consistent channels, output sign, and integral augmentation')
story += [section('6. Transfer functions'),para('Taking Laplace transforms with zero initial conditions gives a 2-by-2 dynamic-stiffness system. Eliminating the body and wheel displacements yields:'),equation(DELTA),para('The output is always S = Zs - Zu. Gu has force input; Gw has road displacement input. Reversing the output to Zu - Zs changes the sign of both transfer functions.'),section('7. Integral augmentation'),equation('xi_dot = C*x\nxa = [x; xi]\nAa = [A, zeros(4,1); C, 0]\nBua = [Bu; 0];  Bwa = [Bw; 0]'),para('Use Bua for controller design and retain Bwa as the disturbance channel. The integral of suspension deflection is distinct from eta. In passive mode the unused integral state has a zero eigenvalue; assess passive mechanical stability using A.'),section('8. Independent consistency checks'),equation('x = T*q + h*zr\nT = [1,         0,  0,      0;\n     0,         1,  0,      0;\n     1,         0, -1,      0;\n     alpha-Ct/Mu, 1, -alpha, -1]\nh = [0; 0; 0; Ct/Mu]\n\nA = T*Ap/T;  Bu = T*bp\nBw = T*wp - A*h;  T*dp + h = 0'),para('The companion validation checks these identities, both transfer functions across a frequency grid, passive stability, and controllability of both the original and integral-augmented actuator plants. See VALIDATION.md for execution details.')]
save('docs/state-space-model.pdf',story)

story=title('PID and LQR Solution Notes','Corrected implementation | Illustrative gains and explicit limitations')
story += [para('Use the corrected model handout and solutions/simulate_quarter_car.m. Parameters and tuning settings are shared through solutions/config.json. This document explains the controller construction; the supplied gains are not asserted to meet every benchmark.'),section('1. Passive baseline'),para('Set u = 0 and compare the resulting body motion, tire deflection, suspension travel and zero actuator effort against both active designs. The four-state mechanical plant is stable. Its slow decay can exceed the 10 s observation interval.'),section('2. Ideal PID on suspension deflection'),equation('u = -Kp*s - Kd*s_dot - Ki*xi,    xi_dot = s\n\nKp = 208000;  Kd = 832000;  Ki = 624000\nK = [Kp*C + Kd*C*A, Ki]\nF = -Kd*C*Bw\nu = -K*xa + F*zr\nAcl = Aa - Bua*K;  Bcl = Bwa + Bua*F'),para('Since C*Bu = 0, recovering s_dot introduces no algebraic control loop. The explicit road term is a coordinate-conversion term; a physical controller can use measured relative velocity instead of measuring road height.'),para('Units: Kp in N/m, Kd in N s/m, and Ki in N/(m s). The example retains the original course gains. A 0.2 m ideal road step causes s_dot to jump to -9.3875 m/s and the derivative force to jump to about 7.81 MN. This illustrates an impractical ideal-PID response, not a feasible actuator design.'),para('For a practical extension, use derivative filtering, smooth road transitions, actuator limits and anti-windup, then re-tune and re-evaluate the model. These extensions are not silently included in the linear reference.'),section('3. Tuning workflow'),para('Study Gu = S/U with zero road disturbance. Use pidTuner or tune gains directly; verify the closed-loop road response separately. Always check closed-loop poles and all metrics. Minimizing suspension deflection can increase body acceleration and actuator force.'),PageBreak()]
story += title('LQR and numerical evaluation','Integral state feedback and exact continuous-input simulation')
story += [section('4. LQR with integral action'),equation('J = integral (xa_transpose*Q*xa + u*R*u) dt\nQ = diag([3e7, 8e7, 8e7, 2e7, 2e10]); R = 0.01\nK = lqr(Aa, Bua, Q, R);  u = -K*xa'),para('The fourth Q entry penalizes eta, not s_dot. Coordinate changes alter the meaning of the weights. The fifth weight penalizes accumulated suspension-deflection error. Increasing R discourages force; changing Q reallocates state penalties. The example assumes full-state availability and no saturation.'),section('5. Simulation and energy integration'),para('The linear closed-loop model is propagated exactly between output times using expm. For a step, append a constant road state and change it at t = 1 s. For a sine, append the oscillator states zr and zr_dot. This avoids replacing a continuous sine with a staircase input.'),equation('z_dot = H*z,    z(t+dt) = E*z(t),    E = expm(H*dt)\ny = h*z\nenergy_interval = z(t)_transpose * G * z(t)\nG = integral_0^dt expm(H_transpose*tau)*h_transpose*h\n    *expm(H*tau) dtau'),para('G is computed with a block matrix exponential. Sum interval energies and divide by T before taking a square root. This accounts for fast PID transients that would be misestimated by applying a trapezoid directly to a coarse sampled spike. Peak and recovery metrics remain sampled at 1 ms.'),section('6. Interpreting the results'),para('Compare the checked-in tables and figures for both road inputs. LQR reduces body acceleration relative to the passive baseline for these settings, but travel and force targets may still be missed. The ideal PID strongly suppresses suspension deflection while demanding excessive force. These conclusions concern the tested nominal parameters, not proven robustness.'),para('Report suspension recovery in the stated +/-4 mm band. Body overshoot and body settling are separate supplemental metrics. Percentage overshoot relative to a zero final suspension deflection is undefined.'),PageBreak()]
story += title('Reference results','Generated from the corrected model and shared configuration')
results=json.loads((ROOT/'solutions/results.json').read_text())
labels=[('acceleration_rms_m_s2','Body acceleration RMS (m/s^2)'),('tire_deflection_rms_m','Tire deflection RMS (m)'),('max_suspension_deflection_m','Peak suspension deflection (m)'),('force_rms_kN','Force RMS (kN)'),('force_peak_kN','Peak force (kN)'),('body_overshoot_percent','Body overshoot (%)'),('body_settling_time_s','Body settling time (s)'),('suspension_recovery_time_s','Suspension recovery time (s)')]
for road in ['step','sine']:
    rows=[['Metric','Passive','PID','LQR']]
    for key,label in labels:
        vals=[results[road][mode][key] for mode in ['NONE','PID','LQR']]
        fmt=lambda v: 'N/A' if v is None else v if isinstance(v,str) else f'{v:.4g}'
        rows.append([label]+[fmt(v) for v in vals])
    story += [section(road.capitalize()+' input'),table(rows,[228,98,98,98])]
story += [para('RMS values span 10 s. "Not settled" means not within the specified band at the end of the record. Sampling affects reported peaks and recovery times; RMS values use exact interval integration. See solutions/results.json for full precision and VALIDATION.md for checks and runtime limitations.')]
save('solutions/solution-notes.pdf',story)
print('Built three corrected PDFs.')
